import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar";
import NextTopLoader from "nextjs-toploader";

const quickSand = Quicksand({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${quickSand.className} antialiased`}>
        <NextTopLoader color="#DD2222"/>
        <Sidebar />
        <div className="p-4 sm:ml-64">
          <div className="p-4 rounded-lg dark:border-gray-700">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}